# coding: utf-8

"""
    Basic Calculator

    Arithmetics is just a call away!  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_5b5b2152dfc9bc0c2ce743a7(self):
        """Test case for 5b5b2152dfc9bc0c2ce743a7

        Add two integers  # noqa: E501
        """
        pass

    def test_5b5b2152dfc9bc0c2ce743a8(self):
        """Test case for 5b5b2152dfc9bc0c2ce743a8

        Subtract two integers  # noqa: E501
        """
        pass

    def test_5b5b2152dfc9bc0c2ce743a9(self):
        """Test case for 5b5b2152dfc9bc0c2ce743a9

        Multiply two integers  # noqa: E501
        """
        pass

    def test_5b5b2152dfc9bc0c2ce743aa(self):
        """Test case for 5b5b2152dfc9bc0c2ce743aa

        Divide two integers  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
